/*
 * INTEL CONFIDENTIAL
 *
 * Copyright (C) 2017 - 2020 Intel Corporation.
 * All Rights Reserved.
 *
 * The source code contained or described herein and all documents
 * related to the source code ("Material") are owned by Intel Corporation
 * or licensors. Title to the Material remains with Intel
 * Corporation or its licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material may
 * be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No License under any patent, copyright, trade secret or other intellectual
 * property right is granted to or conferred upon you by disclosure or
 * delivery of the Materials, either expressly, by implication, inducement,
 * estoppel or otherwise. Any license under such intellectual property rights
 * must be express and approved by Intel in writing.
 */

#ifndef __ISL_PS_RBM_MANIFEST_H
#define __ISL_PS_RBM_MANIFEST_H

#include "ia_css_progdesc_acc_symbol_ids.h"
#include "isl_ps_rbm_terminal_ids.h"
#include "vied_nci_psys_resource_model_private.h"

enum ISL_PS_RBM_DEVICE_ID {
	ISL_PS_RBM_DEVICE_ID_ISA_VIDEO_SCALED_A_RES_OUT_S2V_DEV = VIED_NCI_S2V_ISA_SCALED0_YUV420_ID,
#if HAS_FF_R2I_DS_B
	ISL_PS_RBM_DEVICE_ID_ISA_VIDEO_SCALED_B_RES_OUT_S2V_DEV = VIED_NCI_S2V_ISA_SCALED1_YUV420_ID,
#endif
	ISL_PS_RBM_DEVICE_ID_DEC400_ISL_PS_IN_DEV = VIED_NCI_DEVICE_ID_DEC400,
#if HAS_FF_DOL_DOL
	ISL_PS_RBM_DEVICE_ID_DEC400_ISL_PS_IN_SHORT_DEV = VIED_NCI_DEVICE_ID_DEC400,
	ISL_PS_RBM_DEVICE_ID_DEC400_ISL_PS_IN_MEDIUM_DEV = VIED_NCI_DEVICE_ID_DEC400,
#endif
	ISL_PS_RBM_DEVICE_ID_CIO2STR_PAF = VIED_NCI_DEVICE_ID_CIO2STR,
	ISL_PS_RBM_DEVICE_ID_CIO2STR = VIED_NCI_DEVICE_ID_CIO2STR,
	ISL_PS_RBM_DEVICE_ID_PIFCONV_CTRL_ISL_PAF_A = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISL_PS_RBM_DEVICE_ID_PIFCONV_CTRL_ISL_PAF_B = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISL_PS_RBM_DEVICE_ID_PIFCONV_CTRL_ISL_A = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISL_PS_RBM_DEVICE_ID_PIFCONV_CTRL_ISL_B = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISL_PS_RBM_DEVICE_ID_ISA_ORIG_RES_OUT_S2V_DEV = VIED_NCI_S2V_ISA_ORIG_BAYER_ID,
	ISL_PS_RBM_DEVICE_ID_ISA_VIDEO_FULL_OUT_S2V_DEV = VIED_NCI_S2V_ISA_FULL_YUV420_ID,
	ISL_PS_RBM_DEVICE_ID_ISA_SIS_A_OUT_STR2MMIO = VIED_NCI_PIXEL_STR2MMIO_SIS_A,
	ISL_PS_RBM_DEVICE_ID_ISA_SIS_B_OUT_STR2MMIO = VIED_NCI_PIXEL_STR2MMIO_SIS_B,
	ISL_PS_RBM_DEVICE_ID_ISA_IR_DEPTH_OUT_STR2MMIO = VIED_NCI_PIXEL_STR2MMIO_IR_DEPTH,
	ISL_PS_RBM_DEVICE_ID_ISA_SIS_A_OUT_ACB_DEV = VIED_NCI_DEVICE_ID_LB_ACB,
	ISL_PS_RBM_DEVICE_ID_ISA_SIS_B_OUT_ACB_DEV = VIED_NCI_DEVICE_ID_LB_ACB,
	ISL_PS_RBM_DEVICE_ID_ACB_DEV = VIED_NCI_DEVICE_ID_LB_ACB,
	ISL_PS_RBM_DEVICE_ID_ISA_VIDEO_SCALED_A_RES_OUT_STRM_PACK_DEV = VIED_NCI_STRM_PACK_SCALED_A,
#if HAS_FF_R2I_DS_B
	ISL_PS_RBM_DEVICE_ID_ISA_VIDEO_SCALED_B_RES_OUT_STRM_PACK_DEV = VIED_NCI_STRM_PACK_SCALED_B,
#endif
	ISL_PS_RBM_DEVICE_ID_ISA_VIDEO_FULL_OUT_STRM_PACK_DEV = VIED_NCI_STRM_PACK_VIDEO_FULL,
#if HAS_FF_DOL_DOL
	ISL_PS_RBM_DEVICE_ID_CIO2STR_SHORT = VIED_NCI_DEVICE_ID_CIO2STR,
	ISL_PS_RBM_DEVICE_ID_CIO2STR_MEDIUM = VIED_NCI_DEVICE_ID_CIO2STR,
	ISL_PS_RBM_DEVICE_ID_PIFCONV_CTRL_ISL_SHORT_A = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISL_PS_RBM_DEVICE_ID_PIFCONV_CTRL_ISL_SHORT_B = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISL_PS_RBM_DEVICE_ID_PIFCONV_CTRL_ISL_MEDIUM_A = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISL_PS_RBM_DEVICE_ID_PIFCONV_CTRL_ISL_MEDIUM_B = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
#endif
	ISL_PS_RBM_DEVICE_ID_ISA_ORIG_RES_OUT_STREAM_BLOCKER_DEV = VIED_NCI_DEVICE_ID_STREAM_BLOCKER,
	ISL_PS_RBM_DEVICE_ID_ISA_VIDEO_FULL_OUT_STREAM_BLOCKER_DEV = VIED_NCI_DEVICE_ID_STREAM_BLOCKER,
	ISL_PS_RBM_DEVICE_ID_ISA_IR_DEPTH_OUT_STREAM_BLOCKER_DEV = VIED_NCI_DEVICE_ID_STREAM_BLOCKER,
	ISL_PS_RBM_DEVICE_ID_ISA_SIS_A_OUT_STREAM_BLOCKER_DEV = VIED_NCI_DEVICE_ID_STREAM_BLOCKER,
	ISL_PS_RBM_DEVICE_ID_ISA_SIS_B_OUT_STREAM_BLOCKER_DEV = VIED_NCI_DEVICE_ID_STREAM_BLOCKER,
};

/* KERNEL ids */
enum ISL_PS_RBM_KERNEL_ID {
	/* The following ISP kernels have IDs as high as possible such that
	 * they do not conflict with FF kernel IDs.
	 * We put a '_' before the kernel names because a kernel name is not
	 * allowed to start with a number.
	 */
	ISL_PS_RBM_KERNEL_ID_FF_INL_FF			= KERNEL_ID_ICA_INL,
	ISL_PS_RBM_KERNEL_ID_BLC_GLOBAL_FF		= KERNEL_ID_ICA_BLC_GLOBAL,
	ISL_PS_RBM_KERNEL_ID_BLC_GRID_OB_FF		= KERNEL_ID_BLC_GRID_OB_FF,
	ISL_PS_RBM_KERNEL_ID_FF_PCLN_HDR_FF		= KERNEL_ID_PCLN_HDR,
	ISL_PS_RBM_KERNEL_ID_LSC_HDR_FF	= KERNEL_ID_LSC_HDR,
	ISL_PS_RBM_KERNEL_ID_FF_PEXT_FF			= KERNEL_ID_GDDPC_PEXT_PEXT,
	ISL_PS_RBM_KERNEL_ID_FF_GDDPC_PEXT_FF		= KERNEL_ID_GDDPC_PEXT,
	ISL_PS_RBM_KERNEL_ID_SAM_FF			= KERNEL_ID_GDDPC_PEXT_SAM,
	ISL_PS_RBM_KERNEL_ID_ISA_DM_FF			= KERNEL_ID_B2R_DEMOSAIC,
#if HAS_FF_B2R_BNR
	ISL_PS_RBM_KERNEL_ID_BNR_FF			= KERNEL_ID_B2R_BNR,
#endif
	ISL_PS_RBM_KERNEL_ID_FF_WBA_4PPC_FF		= KERNEL_ID_B2B_WBA,
	ISL_PS_RBM_KERNEL_ID_FF_LCA_FF			= KERNEL_ID_B2B_LCA,
#if HAS_FF_R2I_CCM
	ISL_PS_RBM_KERNEL_ID_FF_R2I_CCM_FF		= KERNEL_ID_R2I_SIE_CCM,
#endif
	ISL_PS_RBM_KERNEL_ID_FF_R2I_CSC_FF		= KERNEL_ID_R2I_SIE_CSC,
#if HAS_FF_R2I_USM
	ISL_PS_RBM_KERNEL_ID_FF_R2I_USM_FF		= KERNEL_ID_R2I_SIE_USM,
#endif
#if HAS_FF_R2I_GTM
	ISL_PS_RBM_KERNEL_ID_FF_R2I_GTM_FF		= KERNEL_ID_R2I_SIE_GTM,
#endif
	ISL_PS_RBM_KERNEL_ID_FF_R2I_DS_A_FF		= KERNEL_ID_R2I_DS_A,
#if HAS_FF_R2I_DS_B
	ISL_PS_RBM_KERNEL_ID_FF_R2I_DS_B_FF		= KERNEL_ID_R2I_DS_B,
#endif
	ISL_PS_RBM_KERNEL_ID_FF_AWB_STATISTICS_FF	= KERNEL_ID_AWB_STAT,
	ISL_PS_RBM_KERNEL_ID_FF_AE_STATISTICS_FF	= KERNEL_ID_AE_STAT,
	ISL_PS_RBM_KERNEL_ID_FF_CCM_3A_FF		= KERNEL_ID_AE_CCM_STAT,
	ISL_PS_RBM_KERNEL_ID_FF_AF_STATISTICS_FF	= KERNEL_ID_AF_STAT,
	ISL_PS_RBM_KERNEL_ID_ISA_ORIG_RES_OUT_STRMPIF_FF_ISA_ORIG		= KERNEL_ID_PIFCONV_ISA_ORIG,
	ISL_PS_RBM_KERNEL_ID_ISA_VIDEO_SCALED_A_RES_OUT_STRMPIF_FF_ISA_SCALED_A	= KERNEL_ID_PIFCONV_ISA_SCALED_A,
#if HAS_FF_R2I_DS_B
	ISL_PS_RBM_KERNEL_ID_ISA_VIDEO_SCALED_B_RES_OUT_STRMPIF_FF_ISA_SCALED_B	= KERNEL_ID_PIFCONV_ISA_SCALED_B,
#endif
	ISL_PS_RBM_KERNEL_ID_ISA_VIDEO_FULL_OUT_STRMPIF_FF_ISA_VIDEO_FULL_OUT	= KERNEL_ID_PIFCONV_ISA_FULL_OUT,
	ISL_PS_RBM_KERNEL_ID_ISA_IR_DEPTH_OUT_PIF_IR_DEPTH			= KERNEL_ID_PIFCONV_ISA_IR_DEPTH,
	ISL_PS_RBM_KERNEL_ID_ISA_ORIG_RES_OUT_ESPA_ISA_ORIG_OUT			= KERNEL_ID_ESPA_ORIG_OUT,
	ISL_PS_RBM_KERNEL_ID_ISA_VIDEO_SCALED_A_RES_OUT_ESPA_ISA_SCALED_A_OUT	= KERNEL_ID_ESPA_SCALED_A,
#if HAS_FF_R2I_DS_B
	ISL_PS_RBM_KERNEL_ID_ISA_VIDEO_SCALED_B_RES_OUT_ESPA_ISA_SCALED_B_OUT	= KERNEL_ID_ESPA_SCALED_B,
#endif
	ISL_PS_RBM_KERNEL_ID_ISA_VIDEO_FULL_OUT_ESPA_ISA_VIDEO_FULL_OUT		= KERNEL_ID_ESPA_FULL_OUT,
	ISL_PS_RBM_KERNEL_ID_ISA_IR_DEPTH_OUT_ESPA_IR_DEPTH			= KERNEL_ID_ESPA_IR_DEPTH,
	ISL_PS_RBM_KERNEL_ID_ISA_SIS_A_OUT_ESPA_SIS_A				= KERNEL_ID_ESPA_SIS_A,
	ISL_PS_RBM_KERNEL_ID_ISA_SIS_B_OUT_ESPA_SIS_B				= KERNEL_ID_ESPA_SIS_B,
	ISL_PS_RBM_KERNEL_ID_ESPA_B2B_OUT					= KERNEL_ID_ESPA_B2B,
	ISL_PS_RBM_KERNEL_ID_ISA_SIS_A_OUT_STRMCROP_FF_SIS_A			= KERNEL_ID_STRMCROP_SIS_A,
	ISL_PS_RBM_KERNEL_ID_ISA_SIS_B_OUT_STRMCROP_FF_SIS_B			= KERNEL_ID_STRMCROP_SIS_B,
	ISL_PS_RBM_KERNEL_ID_SIS_FF_A						= KERNEL_ID_SIS_A,
	ISL_PS_RBM_KERNEL_ID_SIS_FF_B						= KERNEL_ID_SIS_B,
	ISL_PS_RBM_KERNEL_ID_ISA_SIS_A_OUT_STRMPIF_FF_SIS_A			= KERNEL_ID_PIFCONV_SIS_A,
	ISL_PS_RBM_KERNEL_ID_ISA_SIS_B_OUT_STRMPIF_FF_SIS_B			= KERNEL_ID_PIFCONV_SIS_B,
	ISL_PS_RBM_KERNEL_ID_PIXEL_FORMATTER_HIGH					= KERNEL_ID_PIXEL_FORMATTER_HIGH,
	ISL_PS_RBM_KERNEL_ID_ISA_ORIG_RES_OUT_PADDER_ISA_ORIG_OUT		= KERNEL_ID_PADDER_ISA_ORIG,
	ISL_PS_RBM_KERNEL_ID_ISA_VIDEO_FULL_OUT_PADDER_ISA_FULL_OUT		= KERNEL_ID_PADDER_ISA_FULL,
	ISL_PS_RBM_KERNEL_ID_ISA_VIDEO_SCALED_A_RES_OUT_PADDER_ISA_SCALED_A_OUT	= KERNEL_ID_PADDER_ISA_SCALED_A,
#if HAS_FF_R2I_DS_B
	ISL_PS_RBM_KERNEL_ID_ISA_VIDEO_SCALED_B_RES_OUT_PADDER_ISA_SCALED_B_OUT	= KERNEL_ID_PADDER_ISA_SCALED_B,
#endif
#if HAS_FF_DOL_DOL
	ISL_PS_RBM_KERNEL_ID_FF_DOL_DOL_FF		= KERNEL_ID_DOL,
#endif
	ISL_PS_RBM_KERNEL_ID_FF_X2B_MD_FF		= KERNEL_ID_X2B_MD,
#if HAS_FF_DOL_DOL
	ISL_PS_RBM_KERNEL_ID_FF_INL_SHORT_FF		= KERNEL_ID_ICA_INL_SHORT,
	ISL_PS_RBM_KERNEL_ID_BLC_GLOBAL_SHORT_FF	= KERNEL_ID_ICA_BLC_GLOBAL_SHORT,
	ISL_PS_RBM_KERNEL_ID_FF_PCLN_HDR_SHORT_FF	= KERNEL_ID_ICA_PCLN_HDR_SHORT,
	ISL_PS_RBM_KERNEL_ID_FF_INL_MEDIUM_FF		= KERNEL_ID_ICA_INL_MEDIUM,
	ISL_PS_RBM_KERNEL_ID_BLC_GLOBAL_MEDIUM_FF	= KERNEL_ID_ICA_BLC_GLOBAL_MEDIUM,
	ISL_PS_RBM_KERNEL_ID_FF_PCLN_HDR_MEDIUM_FF	= KERNEL_ID_ICA_PCLN_HDR_MEDIUM,
	ISL_PS_RBM_KERNEL_ID_PIXEL_FORMATTER_SHORT	= KERNEL_ID_PIXEL_FORMATTER_SHORT,
	ISL_PS_RBM_KERNEL_ID_PIXEL_FORMATTER_MEDIUM	= KERNEL_ID_PIXEL_FORMATTER_MEDIUM,
#endif
	ISL_PS_RBM_KERNEL_ID_FF_X2B_SVE_FF		= KERNEL_ID_X2B_SVE,
	ISL_PS_RBM_KERNEL_ID_FF_X2B_RGBIR_FF		= KERNEL_ID_X2B_RGBIR,
	ISL_PS_RBM_KERNEL_ID_FF_PAF_FF			= KERNEL_ID_PAF,
	ISL_PS_RBM_KERNEL_ID_CACHED_PARAMETER_IN,
	ISL_PS_RBM_KERNEL_ID_PROGRAM_INIT,
	ISL_PS_RBM_KERNEL_ID_PROGRAM_CONTROL_INIT,
	ISL_PS_RBM_KERNEL_ID_GET_HIGH,
	ISL_PS_RBM_KERNEL_ID_BLC_GRID,
	ISL_PS_RBM_KERNEL_ID_LSC_GRID,
	ISL_PS_RBM_KERNEL_ID_PUT_BAYER,
	ISL_PS_RBM_KERNEL_ID_PUT_YUV_A,
#if HAS_FF_R2I_DS_B
	ISL_PS_RBM_KERNEL_ID_PUT_YUV_B,
#endif
	ISL_PS_RBM_KERNEL_ID_PUT_VIDEO_FULL,
	ISL_PS_RBM_KERNEL_ID_PUT_IR_DEPTH,
	ISL_PS_RBM_KERNEL_ID_PUT_SIS_A,
	ISL_PS_RBM_KERNEL_ID_PUT_SIS_B,
	ISL_PS_RBM_KERNEL_ID_SPT_3A_STAT_AF,
	ISL_PS_RBM_KERNEL_ID_SPT_3A_STAT_AWB,
	ISL_PS_RBM_KERNEL_ID_SPT_PAF,
	ISL_PS_RBM_KERNEL_ID_CACHED_PARAMETER_OUT_AE_STAT,
#if HAS_FF_DOL_DOL
	ISL_PS_RBM_KERNEL_ID_GET_SHORT,
	ISL_PS_RBM_KERNEL_ID_GET_MEDIUM,
#endif
	ISL_PS_RBM_KERNEL_ID_GET_PAF,
};

#endif /* __ISL_PS_RBM_MANIFEST_H */
