/*
 * INTEL CONFIDENTIAL
 * Copyright (c) 2017 Intel Corporation
 * All Rights Reserved.
 *
 * The source code contained or described herein and all documents related to
 * the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors.Title to the Material remains with Intel
 * Corporation or its suppliers and licensors.The Material may contain trade
 * secrets and proprietary and confidential information of Intel Corporation
 * and its suppliers and licensors, and is protected by worldwide copyright
 * and trade secret laws and treaty provisions.No part of the Material may be
 * used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other intellectual
 * property right is granted to or conferred upon you by disclosure or
 * delivery of the Materials, either expressly, by implication, inducement,
 * estoppel or otherwise. Any license under such intellectual property rights
 * must be express and approved by Intel in writing.
 *
 * Unless otherwise agreed by Intel in writing, you may not remove or alter
 * this notice or any other notice embedded in Materials by Intel or Intels
 * suppliers or licensors in any way.
 */

/*! Generated by pfw_ff_writer.py ver. 0.45 */


#ifndef __IA_CSS_FF_AF_STATISTICS_PARAM_DEFS_H
#define __IA_CSS_FF_AF_STATISTICS_PARAM_DEFS_H


#define IA_P2P_PARAM_IN_TERMINAL_FF_AF_STATISTICS_SECTION_COUNT    2
#define IA_P2P_PARAM_IN_TERMINAL_FF_AF_STATISTICS_SECTION_0_SIZE   (0x38)
#define IA_P2P_PARAM_IN_TERMINAL_FF_AF_STATISTICS_DEST_OFFSET_SECTION_0   (0x0)
#define IA_P2P_PARAM_IN_TERMINAL_FF_AF_STATISTICS_SECTION_1_SIZE   (0x60)
#define IA_P2P_PARAM_IN_TERMINAL_FF_AF_STATISTICS_DEST_OFFSET_SECTION_1   (0x80)
#define IA_P2P_PROGRAM_TERMINAL_FF_AF_STATISTICS_SECTION_COUNT    1
#define IA_P2P_PROGRAM_TERMINAL_FF_AF_STATISTICS_SECTION_0_SIZE   (0xc)
#define IA_P2P_PROGRAM_TERMINAL_FF_AF_STATISTICS_DEST_OFFSET_SECTION_0   (0x40)

#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_SECTION_COUNT	(2)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_COMPUTE_UNITS_PER_ELEM					(1)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_MAX_COMPUTE_UNITS_PER_SLICE			(32)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH		(16)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH		(32)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT		(16)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT		(32)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_MAX_SLICE_SIZE_SECTION_0				(0x100)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_ELEM_SIZE_SECTION_0					(0x8)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_SLICE_0_DEST_OFFSET_SECTION_0			(0x100)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_NEXT_SLICE_OFFSET_SECTION_0			(0x100)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_MAX_SLICE_SIZE_SECTION_1				(0x100)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_ELEM_SIZE_SECTION_1					(0x8)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_SLICE_0_DEST_OFFSET_SECTION_1			(0x300)
#define IA_P2P_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AF_NEXT_SLICE_OFFSET_SECTION_1			(0x100)


#endif /* __IA_CSS_FF_AF_STATISTICS_PARAM_DEFS_H */

