/*
 * INTEL CONFIDENTIAL
 *
 * Copyright (C) 2017 - 2020 Intel Corporation.
 * All Rights Reserved.
 *
 * The source code contained or described herein and all documents
 * related to the source code ("Material") are owned by Intel Corporation
 * or licensors. Title to the Material remains with Intel
 * Corporation or its licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material may
 * be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No License under any patent, copyright, trade secret or other intellectual
 * property right is granted to or conferred upon you by disclosure or
 * delivery of the Materials, either expressly, by implication, inducement,
 * estoppel or otherwise. Any license under such intellectual property rights
 * must be express and approved by Intel in writing.
 */

#ifndef __ISA_LB_MANIFEST_H
#define __ISA_LB_MANIFEST_H

#include "ia_css_progdesc_acc_symbol_ids.h"
#include "isa_lb_terminal_ids.h"
#include "vied_nci_psys_resource_model_private.h"

enum ISA_LB_DEVICE_ID {
	ISA_LB_DEVICE_ID_S2V_SCALED_A_S2V_DEV = VIED_NCI_S2V_ISA_SCALED0_YUV420_ID,
#if HAS_FF_R2I_DS_B
	ISA_LB_DEVICE_ID_S2V_SCALED_B_S2V_DEV = VIED_NCI_S2V_ISA_SCALED1_YUV420_ID,
#endif
	ISA_LB_DEVICE_ID_DEC400_ISL_PS_IN_DEV = VIED_NCI_DEVICE_ID_DEC400,
#if HAS_FF_DOL_DOL
	ISA_LB_DEVICE_ID_DEC400_ISL_PS_IN_SHORT_DEV = VIED_NCI_DEVICE_ID_DEC400,
	ISA_LB_DEVICE_ID_DEC400_ISL_PS_IN_MEDIUM_DEV = VIED_NCI_DEVICE_ID_DEC400,
#endif
	ISA_LB_DEVICE_ID_CIO2STR_PAF = VIED_NCI_DEVICE_ID_CIO2STR,
	ISA_LB_DEVICE_ID_CIO2STR = VIED_NCI_DEVICE_ID_CIO2STR,
	ISA_LB_DEVICE_ID_PIFCONV_CTRL_ISL_PAF_A = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISA_LB_DEVICE_ID_PIFCONV_CTRL_ISL_PAF_B = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISA_LB_DEVICE_ID_PIFCONV_CTRL_ISL_A = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISA_LB_DEVICE_ID_PIFCONV_CTRL_ISL_B = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISA_LB_DEVICE_ID_S2V_ORIG_RES_S2V_DEV = VIED_NCI_S2V_ISA_ORIG_BAYER_ID,
	ISA_LB_DEVICE_ID_S2V_VIDEO_FULL_S2V_DEV = VIED_NCI_S2V_ISA_FULL_YUV420_ID,
	ISA_LB_DEVICE_ID_ISA_SIS_A_OUT_STR2MMIO = VIED_NCI_PIXEL_STR2MMIO_SIS_A,
	ISA_LB_DEVICE_ID_ISA_SIS_B_OUT_STR2MMIO = VIED_NCI_PIXEL_STR2MMIO_SIS_B,
	ISA_LB_DEVICE_ID_ISA_IR_DEPTH_OUT_STR2MMIO = VIED_NCI_PIXEL_STR2MMIO_IR_DEPTH,
	ISA_LB_DEVICE_ID_ACB_DEV = VIED_NCI_DEVICE_ID_LB_ACB,
	ISA_LB_DEVICE_ID_S2V_DEV = VIED_NCI_DEVICE_ID_LB_ACB,
	ISA_LB_DEVICE_ID_ISA_VIDEO_SCALED_A_RES_OUT_STRM_PACK_DEV = VIED_NCI_STRM_PACK_SCALED_A,
#if HAS_FF_R2I_DS_B
	ISA_LB_DEVICE_ID_ISA_VIDEO_SCALED_B_RES_OUT_STRM_PACK_DEV = VIED_NCI_STRM_PACK_SCALED_B,
#endif
	ISA_LB_DEVICE_ID_ISA_VIDEO_FULL_OUT_STRM_PACK_DEV = VIED_NCI_STRM_PACK_VIDEO_FULL,
	ISA_LB_DEVICE_ID_PSA_STR2VEC_H_OUT_STRM_PACK_DEV = VIED_NCI_STRM_PACK_STR2VEC_H,
	ISA_LB_DEVICE_ID_DVS_CONTROLLER_DEV = VIED_NCI_DEVICE_ID_DVS_CONTROLLER,
	ISA_LB_DEVICE_ID_DEC400_PSA_OUT_DEV = VIED_NCI_DEVICE_ID_DEC400,
#if HAS_FF_DOL_DOL
	ISA_LB_DEVICE_ID_CIO2STR_SHORT = VIED_NCI_DEVICE_ID_CIO2STR,
	ISA_LB_DEVICE_ID_CIO2STR_MEDIUM = VIED_NCI_DEVICE_ID_CIO2STR,
	ISA_LB_DEVICE_ID_PIFCONV_CTRL_ISL_SHORT_A = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISA_LB_DEVICE_ID_PIFCONV_CTRL_ISL_SHORT_B = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISA_LB_DEVICE_ID_PIFCONV_CTRL_ISL_MEDIUM_A = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
	ISA_LB_DEVICE_ID_PIFCONV_CTRL_ISL_MEDIUM_B = VIED_NCI_DEVICE_ID_PIFCONV_CTRL,
#endif
	ISA_LB_DEVICE_ID_ISA_ORIG_RES_OUT_STREAM_BLOCKER_DEV = VIED_NCI_DEVICE_ID_STREAM_BLOCKER,
	ISA_LB_DEVICE_ID_ISA_VIDEO_FULL_OUT_STREAM_BLOCKER_DEV = VIED_NCI_DEVICE_ID_STREAM_BLOCKER,
	ISA_LB_DEVICE_ID_ISA_IR_DEPTH_OUT_STREAM_BLOCKER_DEV = VIED_NCI_DEVICE_ID_STREAM_BLOCKER,
	ISA_LB_DEVICE_ID_ISA_SIS_A_OUT_STREAM_BLOCKER_DEV = VIED_NCI_DEVICE_ID_STREAM_BLOCKER,
	ISA_LB_DEVICE_ID_ISA_SIS_B_OUT_STREAM_BLOCKER_DEV = VIED_NCI_DEVICE_ID_STREAM_BLOCKER,
	ISA_LB_DEVICE_ID_V2S_INPUT_V2S_DEV = VIED_NCI_V2S_LBFF_INFRA_VEC2STR_1_ID,
};

/* KERNEL ids */
enum ISA_LB_KERNEL_ID {
	/* The following ISP kernels have IDs as high as possible such that
	 * they do not conflict with FF kernel IDs.
	 * We put a '_' before the kernel names because a kernel name is not
	 * allowed to start with a number.
	 */

	/* Add spare kernels in order to get correct results from haaf_align script. */
	/* ISA_LB_KERNEL_ID_SPARE1_FF                  = KERNEL_ID_SPARE, */
	/* ISA_LB_KERNEL_ID_SPARE2_FF                  = KERNEL_ID_SPARE, */
	/* ISA_LB_KERNEL_ID_SPARE3_FF                  = KERNEL_ID_SPARE, */
	ISA_LB_KERNEL_ID_BNLM_FF                  = KERNEL_ID_RYNR_BNLM,
	ISA_LB_KERNEL_ID_DM_FF                    = KERNEL_ID_DEMOSAIC_DEMOSAIC,
#if HAS_ACM_CCM
	ISA_LB_KERNEL_ID_CCM_FF                   = KERNEL_ID_ACM_CCM,
#else
	/* ISA_LB_KERNEL_ID_NO_CCM_SPARE             = KERNEL_ID_NO_CCM_SPARE, */
#endif
	ISA_LB_KERNEL_ID_ACM_FF                   = KERNEL_ID_ACM_ACM,
#if HAS_VCR_IN_VCA
	ISA_LB_KERNEL_ID_VCR2_FF                  = KERNEL_ID_VCA_VCR2,
#else
	/* ISA_LB_KERNEL_ID_NO_VCR2_SPARE            = KERNEL_ID_NO_VCR2_SPARE, */
#endif
	ISA_LB_KERNEL_ID_GAMMASTAR_FF             = KERNEL_ID_GAMMASTAR,
	ISA_LB_KERNEL_ID_CSC_CDS_FF               = KERNEL_ID_GTC_CSC_CDS,
	ISA_LB_KERNEL_ID_FF_GAMMA_TM_FF           = KERNEL_ID_GTC_GTM,
	ISA_LB_KERNEL_ID_YUV_SPLITTER_FF          = KERNEL_ID_YUV1_SPLITTER,
	ISA_LB_KERNEL_ID_IEFD_FF                  = KERNEL_ID_YUV1_IEFD,
	/* ISA_LB_KERNEL_ID_SPARE4_FF                  = KERNEL_ID_SPARE, */
	/* ISA_LB_KERNEL_ID_SPARE5_FF                  = KERNEL_ID_SPARE, */
	ISA_LB_KERNEL_ID_Y_BIN_FF                 = KERNEL_ID_DVS_YBIN,
	ISA_LB_KERNEL_ID_DVS_FF                   = KERNEL_ID_DVS_DVS,
	ISA_LB_KERNEL_ID_VCSC_FF                  = KERNEL_ID_VCSC,
	ISA_LB_KERNEL_ID_GLTM_FF                  = KERNEL_ID_GLTM,
	ISA_LB_KERNEL_ID_XNR5_VHF_FF              = KERNEL_ID_XNR_VHF,
	ISA_LB_KERNEL_ID_XNR5_HF_FF               = KERNEL_ID_XNR_HF,
	ISA_LB_KERNEL_ID_XNR5_SE_FF               = KERNEL_ID_XNR_HF_SE,
	ISA_LB_KERNEL_ID_XNR5_MF_FF               = KERNEL_ID_XNR_MF,
	ISA_LB_KERNEL_ID_XNR5_SE_MF_FF            = KERNEL_ID_XNR_MF_SE,
	ISA_LB_KERNEL_ID_XNR5_LF_FF               = KERNEL_ID_XNR_LF,
	ISA_LB_KERNEL_ID_XNR5_SE_LF_FF            = KERNEL_ID_XNR_LF_SE,
	ISA_LB_KERNEL_ID_XNR5_LFE_FF              = KERNEL_ID_XNR_LFE,
	ISA_LB_KERNEL_ID_XNR5_VLF_FF              = KERNEL_ID_XNR_VLF,
	ISA_LB_KERNEL_ID_XNR5_SE_VLF_FF           = KERNEL_ID_XNR_VLF_SE,
#if !HAS_VCR_IN_VCA
	ISA_LB_KERNEL_ID_VCR_FF                   = KERNEL_ID_XNR_VCR,
#endif
	ISA_LB_KERNEL_ID_ESPA_FF                  = KERNEL_ID_ESPA,
	ISA_LB_KERNEL_ID_ESPA_V2S_PSA_1_FF        = KERNEL_ID_ESPA_V2S_PSA_1,
	ISA_LB_KERNEL_ID_GLIM_FF                  = KERNEL_ID_ACM_GLIM,
	ISA_LB_KERNEL_ID_STRMCROP_FF_PSA_H        = KERNEL_ID_STREAM_CROP_PSA_H,
	ISA_LB_KERNEL_ID_DVS_STATS_L0             = KERNEL_ID_DVS_STATS_L0,
	ISA_LB_KERNEL_ID_DVS_STATS_L1             = KERNEL_ID_DVS_STATS_L1,
	ISA_LB_KERNEL_ID_DVS_STATS_L2             = KERNEL_ID_DVS_STATS_L2,
	ISA_LB_KERNEL_ID_GAMMASTAR_GRID,
	/* ISA_LB_KERNEL_ID_SPARE7_FF                  = KERNEL_ID_SPARE, */
	/* ISA_LB_KERNEL_ID_SPARE8_FF                  = KERNEL_ID_SPARE, */
	/* ISA_LB_KERNEL_ID_SPARE9_FF                  = KERNEL_ID_SPARE, */
	ISA_LB_KERNEL_ID_FF_INL_FF               = KERNEL_ID_ICA_INL,
	ISA_LB_KERNEL_ID_BLC_GLOBAL_FF            = KERNEL_ID_ICA_BLC_GLOBAL,
	ISA_LB_KERNEL_ID_BLC_GRID_OB_FF           = KERNEL_ID_BLC_GRID_OB_FF,
	ISA_LB_KERNEL_ID_FF_PCLN_HDR_FF           = KERNEL_ID_PCLN_HDR,
	ISA_LB_KERNEL_ID_LSC_HDR_FF               = KERNEL_ID_LSC_HDR,
	ISA_LB_KERNEL_ID_FF_PEXT_FF               = KERNEL_ID_GDDPC_PEXT_PEXT,
	ISA_LB_KERNEL_ID_FF_GDDPC_PEXT_FF         = KERNEL_ID_GDDPC_PEXT,
	ISA_LB_KERNEL_ID_SAM_FF                   = KERNEL_ID_GDDPC_PEXT_SAM,
	ISA_LB_KERNEL_ID_ISA_DM_FF                = KERNEL_ID_B2R_DEMOSAIC,
#if HAS_FF_B2R_BNR
	ISA_LB_KERNEL_ID_BNR_FF                   = KERNEL_ID_B2R_BNR,
#endif
	ISA_LB_KERNEL_ID_FF_WBA_4PPC_FF           = KERNEL_ID_B2B_WBA,
	ISA_LB_KERNEL_ID_FF_LCA_FF                = KERNEL_ID_B2B_LCA,
#if HAS_FF_R2I_CCM
	ISA_LB_KERNEL_ID_FF_R2I_CCM_FF            = KERNEL_ID_R2I_SIE_CCM,
#endif
	ISA_LB_KERNEL_ID_FF_R2I_CSC_FF            = KERNEL_ID_R2I_SIE_CSC,
#if HAS_FF_R2I_USM
	ISA_LB_KERNEL_ID_FF_R2I_USM_FF            = KERNEL_ID_R2I_SIE_USM,
#endif
#if HAS_FF_R2I_GTM
	ISA_LB_KERNEL_ID_FF_R2I_GTM_FF            = KERNEL_ID_R2I_SIE_GTM,
#endif
	ISA_LB_KERNEL_ID_FF_R2I_DS_A_FF           = KERNEL_ID_R2I_DS_A,
#if HAS_FF_R2I_DS_B
	ISA_LB_KERNEL_ID_FF_R2I_DS_B_FF           = KERNEL_ID_R2I_DS_B,
#endif
	ISA_LB_KERNEL_ID_FF_AWB_STATISTICS_FF     = KERNEL_ID_AWB_STAT,
	ISA_LB_KERNEL_ID_FF_AE_STATISTICS_FF      = KERNEL_ID_AE_STAT,
	ISA_LB_KERNEL_ID_FF_CCM_3A_FF             = KERNEL_ID_AE_CCM_STAT,
	ISA_LB_KERNEL_ID_FF_AF_STATISTICS_FF      = KERNEL_ID_AF_STAT,
	ISA_LB_KERNEL_ID_ISA_ORIG_RES_OUT_STRMPIF_FF_ISA_ORIG = KERNEL_ID_PIFCONV_ISA_ORIG,
	ISA_LB_KERNEL_ID_ISA_VIDEO_SCALED_A_RES_OUT_STRMPIF_FF_ISA_SCALED_A = KERNEL_ID_PIFCONV_ISA_SCALED_A,
#if HAS_FF_R2I_DS_B
	ISA_LB_KERNEL_ID_ISA_VIDEO_SCALED_B_RES_OUT_STRMPIF_FF_ISA_SCALED_B = KERNEL_ID_PIFCONV_ISA_SCALED_B,
#endif
	ISA_LB_KERNEL_ID_ISA_VIDEO_FULL_OUT_STRMPIF_FF_ISA_VIDEO_FULL_OUT = KERNEL_ID_PIFCONV_ISA_FULL_OUT,
	ISA_LB_KERNEL_ID_ISA_IR_DEPTH_OUT_PIF_IR_DEPTH     = KERNEL_ID_PIFCONV_ISA_IR_DEPTH,
	ISA_LB_KERNEL_ID_ISA_ORIG_RES_OUT_ESPA_ISA_ORIG_OUT = KERNEL_ID_ESPA_ORIG_OUT,
	ISA_LB_KERNEL_ID_ISA_VIDEO_SCALED_A_RES_OUT_ESPA_ISA_SCALED_A_OUT = KERNEL_ID_ESPA_SCALED_A,
#if HAS_FF_R2I_DS_B
	ISA_LB_KERNEL_ID_ISA_VIDEO_SCALED_B_RES_OUT_ESPA_ISA_SCALED_B_OUT = KERNEL_ID_ESPA_SCALED_B,
#endif
	ISA_LB_KERNEL_ID_ISA_VIDEO_FULL_OUT_ESPA_ISA_VIDEO_FULL_OUT = KERNEL_ID_ESPA_FULL_OUT,
	ISA_LB_KERNEL_ID_ISA_IR_DEPTH_OUT_ESPA_IR_DEPTH           = KERNEL_ID_ESPA_IR_DEPTH,
	ISA_LB_KERNEL_ID_ISA_SIS_A_OUT_ESPA_SIS_A = KERNEL_ID_ESPA_SIS_A,
	ISA_LB_KERNEL_ID_ISA_SIS_B_OUT_ESPA_SIS_B = KERNEL_ID_ESPA_SIS_B,
	ISA_LB_KERNEL_ID_ESPA_B2B_OUT             = KERNEL_ID_ESPA_B2B,
	ISA_LB_KERNEL_ID_ISA_SIS_A_OUT_STRMCROP_FF_SIS_A = KERNEL_ID_STRMCROP_SIS_A,
	ISA_LB_KERNEL_ID_ISA_SIS_B_OUT_STRMCROP_FF_SIS_B = KERNEL_ID_STRMCROP_SIS_B,
	ISA_LB_KERNEL_ID_SIS_FF_A = KERNEL_ID_SIS_A,
	ISA_LB_KERNEL_ID_SIS_FF_B = KERNEL_ID_SIS_B,
	ISA_LB_KERNEL_ID_ISA_SIS_A_OUT_STRMPIF_FF_SIS_A = KERNEL_ID_PIFCONV_SIS_A,
	ISA_LB_KERNEL_ID_ISA_SIS_B_OUT_STRMPIF_FF_SIS_B = KERNEL_ID_PIFCONV_SIS_B,
	ISA_LB_KERNEL_ID_PIXEL_FORMATTER_HIGH          = KERNEL_ID_PIXEL_FORMATTER_HIGH,
	ISA_LB_KERNEL_ID_ISA_ORIG_RES_OUT_PADDER_ISA_ORIG_OUT = KERNEL_ID_PADDER_ISA_ORIG,
	ISA_LB_KERNEL_ID_ISA_VIDEO_FULL_OUT_PADDER_ISA_FULL_OUT = KERNEL_ID_PADDER_ISA_FULL,
	ISA_LB_KERNEL_ID_ISA_VIDEO_SCALED_A_RES_OUT_PADDER_ISA_SCALED_A_OUT = KERNEL_ID_PADDER_ISA_SCALED_A,
#if HAS_FF_R2I_DS_B
	ISA_LB_KERNEL_ID_ISA_VIDEO_SCALED_B_RES_OUT_PADDER_ISA_SCALED_B_OUT = KERNEL_ID_PADDER_ISA_SCALED_B,
#endif
#if HAS_FF_DOL_DOL
	ISA_LB_KERNEL_ID_FF_DOL_DOL_FF      = KERNEL_ID_DOL,
#endif
	ISA_LB_KERNEL_ID_FF_X2B_MD_FF      = KERNEL_ID_X2B_MD,
#if HAS_FF_DOL_DOL
	ISA_LB_KERNEL_ID_FF_INL_SHORT_FF = KERNEL_ID_ICA_INL_SHORT,
	ISA_LB_KERNEL_ID_BLC_GLOBAL_SHORT_FF = KERNEL_ID_ICA_BLC_GLOBAL_SHORT,
	ISA_LB_KERNEL_ID_FF_PCLN_HDR_SHORT_FF = KERNEL_ID_ICA_PCLN_HDR_SHORT,
	ISA_LB_KERNEL_ID_FF_INL_MEDIUM_FF = KERNEL_ID_ICA_INL_MEDIUM,
	ISA_LB_KERNEL_ID_BLC_GLOBAL_MEDIUM_FF = KERNEL_ID_ICA_BLC_GLOBAL_MEDIUM,
	ISA_LB_KERNEL_ID_FF_PCLN_HDR_MEDIUM_FF = KERNEL_ID_ICA_PCLN_HDR_MEDIUM,
	ISA_LB_KERNEL_ID_PIXEL_FORMATTER_SHORT = KERNEL_ID_PIXEL_FORMATTER_SHORT,
	ISA_LB_KERNEL_ID_PIXEL_FORMATTER_MEDIUM = KERNEL_ID_PIXEL_FORMATTER_MEDIUM,
#endif
	ISA_LB_KERNEL_ID_FF_X2B_SVE_FF = KERNEL_ID_X2B_SVE,
	ISA_LB_KERNEL_ID_FF_X2B_RGBIR_FF = KERNEL_ID_X2B_RGBIR,
	ISA_LB_KERNEL_ID_FF_PAF_FF = KERNEL_ID_PAF,
	ISA_LB_KERNEL_ID_CACHED_PARAMETER_IN,
	ISA_LB_KERNEL_ID_PROGRAM_INIT,
	ISA_LB_KERNEL_ID_PROGRAM_CONTROL_INIT,
	ISA_LB_KERNEL_ID_GET_HIGH,
	ISA_LB_KERNEL_ID_BLC_GRID,
	ISA_LB_KERNEL_ID_LSC_GRID,
	ISA_LB_KERNEL_ID_PUT_SIS_A,
	ISA_LB_KERNEL_ID_PUT_SIS_B,
	ISA_LB_KERNEL_ID_PUT_BAYER,
#if HAS_FF_R2I_DS_B
	ISA_LB_KERNEL_ID_PUT_YUV_B,
#endif
	ISA_LB_KERNEL_ID_PUT_VIDEO_FULL,
	ISA_LB_KERNEL_ID_PUT_IR_DEPTH,
	ISA_LB_KERNEL_ID_SPT_3A_STAT_AF,
	ISA_LB_KERNEL_ID_SPT_3A_STAT_AWB,
	ISA_LB_KERNEL_ID_SPT_PAF,
	ISA_LB_KERNEL_ID_PUT,
	ISA_LB_KERNEL_ID_CACHED_PARAMETER_OUT_AE_STAT,
#if HAS_FF_DOL_DOL
	ISA_LB_KERNEL_ID_GET_SHORT,
	ISA_LB_KERNEL_ID_GET_MEDIUM,
#endif
	ISA_LB_KERNEL_ID_GET_PAF,
	ISA_LB_KERNEL_ID_VERTICAL_PADDING,
};

#endif /* __ISA_LB_MANIFEST_H */
